### ISSUE TITLE
[Bug]: Edit template name and description - Nothing happens

### ISSUE THREAD

**Issue by xenadmin** [KelvinTegelaar/CIPP#4911]
### Required confirmations before submitting

- [x] **I can reproduce this issue on the latest released versions** of both CIPP and CIPP-API.
- [x] **I have searched existing issues** (both open and closed) to avoid duplicates.
- [x] I am **not** requesting general support; this is an actual bug report.

### Issue Description

1. When we sync OIB templates there are at first in sync:
2. <img width="801" height="635" alt="Image" src="https://github.com/user-attachments/assets/bc2ffad7-7e7f-49a8-ab4f-cbd5b17df23b" />
3. Afterwards, I want to bringt some of them out of sync, as we don't want to use them "as is" but make small adjustments. 
4. In my understanding, that is what "Edit template name and description" is for:
5. <img width="368" height="271" alt="Image" src="https://github.com/user-attachments/assets/29655895-d9d3-4eb7-a638-d7e89fb458e4" />
6. <img width="605" height="373" alt="Image" src="https://github.com/user-attachments/assets/8a167a96-523c-40cd-9c7d-6274f5e36181" />
7. When I change the name and confirm, nothing happens. 
8. Also nothing is written to the Logbook. 

### Environment Type

Sponsored (paying) user

### Front End Version

8.6.1

### Back End Version

8.6.2

### Relevant Logs / Stack Trace

```plaintext

```

**Comment by KelvinTegelaar** [comment]
Fixed in dev

**Comment by xenadmin** [comment]
Today I switched our instance to Dev branch and tested this. I can confirm that, ...

I can rename a template.
I can't duplicate a template. How to do this?
After I run the Template Library sync schedule, everything gets overridden again, bringing me back to the start. 

IMHO this is not fixed and has to be re-opened. 
This is urgent, we still can't use CIPP at all regarding OIB.
